### ISSUE TITLE
Новый алгоритм шифрования

### ISSUE THREAD

**Issue by vanyasem** [vodka2/vkaudio#1]
Сегодня снова завинтили гайки. Ссылки теперь выглядят таким образом: `https://m.vk.com/mp3/audio_api_unavailable.mp3?extra=mMj1zMeUoc1mDM82Auu5DJKVp1KTqwjmy3nSnduOvZvOugG6zs9LCtLkCY9Ov1jHnNvbmJfiudvpwI9fu3rNttfelOrrvwrfu2OOEdD2Cdy1rNaYoefystnRoh0OCZfZA2fsEw1LzvbkCJqOBOi4tMHNELbWqKn4mxPVrLHLqxnktNjtrgf3AJjkBdbyzNPNn3uZwuj1lLLynNHOnZDJywKXn1LpqJzWCwzPswvdCgWUyM9or3PNpxLQtJHKzuO1zfn1AfbJlOzktZfxBKrJrhq4ogC1C1jXmMm#AqSOmZu`. Текущий код можно считать obsolete

**Comment by billionaire** [comment]
It seems that now to decode the URL to the input of the decode-function it is necessary to specify the VK ID for which the link was generated.
![20171122215530ccovf43uqx](https://user-images.githubusercontent.com/6255854/33151406-aa7c92c0-cfe0-11e7-9cd8-137765f8ed5a.png)

**Comment by vanyasem** [comment]
thank you for pointing out at the functions. i will take a look at it later when i get home

**Comment by vodka2** [comment]
Как-то они совсем подло поступили, внесли изменения, пока я спал. Вроде сейчас работает. Если нет, то приводите не только URI, но и ваш Id вконтакте (можно личным сообщением на Тостере)

**Comment by vanyasem** [comment]
на этом коде базируется vk_api. он тоже внезапно полетел, и туда issue влепить успели )

**Comment by vanyasem** [comment]
я поражён скоростью разрешения проблемы, огромный респект

**Comment by vanyasem** [comment]
это водочка такие супер-силы придаёт? ;)

**Comment by vodka2** [comment]
@vanyasem Так изменилось-то совсем немного, если посмотреть diff. Спасибо за «звезду»! Надо в vk_api написать.

**Comment by vanyasem** [comment]
@vodka2 vk_api сам алгоритм берёт. там на пайтоне переписано. я займусь

**Comment by vodka2** [comment]
@vanyasem я тоже хочу аналогичный алгоритм (расшифровки) на Python сюда добавить, я бы смог его поддерживать. Всё-таки Python популярный язык. Или, если есть желание, вы могли бы сделать сюда PR. :)

**Comment by vanyasem** [comment]
@vodka2 код я подправил в репо vk_api, см мой PR там. файл с python декодером - `audio_url_decoder.py`. его, в принципе, можно пульнуть в это репо, надо бы только изначального автора этого кода спросить

**Comment by vodka2** [comment]
@vanyasem Меня не очень устраивает этот код (однобуквенные переменные, splice, например), да и он не для всех адресов работает (даже для [примера](https://github.com/vodka2/vkaudio/blob/master/enc_code.html) из скрипта шифровки). Я лучше укажу ссылку в README.

**Comment by vanyasem** [comment]
Однобуквенные переменные совпадают с кодом из ВК, чтобы было легче при изменениях фиксить

**Comment by vanyasem** [comment]
Что касается не для всех адресов -- первый раз такое слышу, никто не жаловался

**Comment by vodka2** [comment]
@vanyasem Я же привёл конкретный пример. Скрипт ВК на нём работает правильно, мой код тоже. Хотя возможно, на сайте Контакта таких адресов пока нет. А однобуквенные переменные в скрипте получены от минификатора, уже один раз менялись, по-моему.

**Comment by vanyasem** [comment]
Я уточню, надо смотреть мой форк (мой ПР), в апстриме пока старая версия. Новая работает исправно и там даже 2 примера висит

**Comment by vanyasem** [comment]
Про минификатор понятно, например, в этот раз не изменились, было достаточно лишь копипастнуть строку. Так проще, имхо

**Comment by vodka2** [comment]
@vanyasem Я как раз имел в виду ваш PR.

**Comment by vanyasem** [comment]
у нас всё работает ) если есть какая-то проблема - можно открыть issue и уже подробно описать, что же пошло не так, я поправлю. за ссылку спасибо

![2017-11-24-072437_1714x301_scrot](https://user-images.githubusercontent.com/13350458/33195449-ae42f332-d0e8-11e7-9a33-2ef207562b5f.png)
